### ISSUE TITLE
Update for SDK 31

### ISSUE THREAD

**Issue by poptocrack** [xcarpentier/ex-react-native-i18n#15]
Hey,

Could you update the plugin to remove the SDK 31 warning?

With the SDK 31, they changed the way Localization works:

> Revamped Localization module
Our Localization module has been completely rewritten to work better with community libraries like i18n-js. We now expose most information synchronously so that your app can localize immediately instead of waiting for an asynchronous bridge call. Check out the updated docs.

The plugin now throw a warning:
`Expo.DangerZone.Localization.getCurrentLocaleAsync() is deprecated. Use Expo.Localization.locale instead.`

The [new documentation](https://docs.expo.io/versions/v31.0.0/sdk/localization)

Thanks!

**Comment by xcarpentier** [comment]
HI,
Thanks for advice !
Will change it soon or maybe PR it, it's open

**Comment by jordyvanraaij** [comment]
@xcarpentier I created a pull request including a fix for the `import Expo from` deprecation warning #17

**Comment by Asthor** [comment]
Can you publish the 0.0.6 version on npm please?
Thanks.
BR
