### ISSUE TITLE
'await' is a reserved word

### ISSUE THREAD

**Issue by MarcJohansenITM** [xcarpentier/ex-react-native-i18n#2]
When following the guidelines from the readme:
...
componentWillMount() {
    await I18n.initAsync();
}
...

I get the error 'await is a reserved word'.

Using Expo 16.0.0 and 'ex-react-native-i18n' v. 0.0.3.

(If i'm missing some info, please let me now)

**Comment by xcarpentier** [comment]
Sorry, just add async.

```javascript
async componentWillMount() {
  await I18n.initAsync();
}
```

**Comment by MarcJohansenITM** [comment]
Cheers - still getting used to the Async Await syntax. :)
